-- Run this in Supabase SQL Editor

-- 1. Create wallets table
create table public.wallets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  emoji text not null,
  color text not null,
  balance bigint not null default 0,
  type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create transactions table
create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  type text not null,
  category text not null,
  "desc" text not null,
  amount bigint not null,
  date text not null,
  wallet_id bigint references public.wallets(id) on delete cascade not null,
  to_wallet_id bigint references public.wallets(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table public.wallets enable row level security;
alter table public.transactions enable row level security;

-- 4. Create Policies
create policy "Users can view their own wallets" on public.wallets for select using (auth.uid() = user_id);
create policy "Users can insert their own wallets" on public.wallets for insert with check (auth.uid() = user_id);
create policy "Users can update their own wallets" on public.wallets for update using (auth.uid() = user_id);
create policy "Users can delete their own wallets" on public.wallets for delete using (auth.uid() = user_id);

create policy "Users can view their own transactions" on public.transactions for select using (auth.uid() = user_id);
create policy "Users can insert their own transactions" on public.transactions for insert with check (auth.uid() = user_id);
create policy "Users can update their own transactions" on public.transactions for update using (auth.uid() = user_id);
create policy "Users can delete their own transactions" on public.transactions for delete using (auth.uid() = user_id);
